const translations = {
    en: {
        "nav-about": "About",
        "nav-fleet": "Fleet & Safety",
        "nav-careers": "Careers",
        "nav-team": "Meet the Team",
        "nav-contact": "Contact",
        "hero-quote-1": "\"We deliver packages for Amazon, we don't bring 'em back!\"",
        "hero-quote-1-author": "- Anthony Laury 2018",
        "hero-quote-4": "\"Delivering packages for Amazon is a job, it’s my job to turn delivery into a career!\"",
        "hero-quote-3": "- Anthony Laury 2023",
        "hero-subtitle": "We are an Amazon DSP building a culture built on safety and efficiency with an eye on the future of logistic. Join our team today.",
        "btn-join": "Join Our Team",
        "btn-contact": "Contact Us",
        
        "sec-about-title": "Our Story",
        "about-who-title": "Who We Are",
        "about-who-text": "A&A Xpress is an independent Delivery Service Partner (DSP) working with Amazon, operating out of Jacksonville, Florida. We are responsible for last-mile delivery operations, ensuring packages reach customers safely and efficiently. Our team is built on structure, accountability, and a commitment to operational excellence.",
        "about-diff-title": "What Makes Us Different",
        "about-diff-text": "At A&A Xpress, we don't just deliver packages — we run a structured, data-driven operation. We use performance metrics and internal systems to make real-time decisions, anticipate challenges, and support our drivers daily. Unlike many DSPs, we offer a clear path for growth. Drivers have the opportunity to advance into leadership roles.",
        "about-values-title": "Our Core Values",
        
        "val-safe": "Safety First",
        "val-safe-desc": " - We prioritize safe driving and responsible delivery at all times.",
        "val-team": "Teamwork",
        "val-team-desc": " - We operate as one team, supporting each other to succeed daily.",
        "val-acc": "Accountability",
        "val-acc-desc": " - We take ownership of our performance and results.",
        "val-grow": "Growth & Development",
        "val-grow-desc": " - We provide opportunities for career advancement within the company.",
        "val-exc": "Excellence in Execution",
        "val-exc-desc": " - We aim to deliver at the highest standard, every day.",

        "sec-fleet-title": "Fleet Readiness & Operations",
        "fleet-edv": "Rivian EDVs",
        "fleet-edv-desc": "The majority of our fleet, pushing zero-emission logistics forward.",
        "fleet-cdv": "CDVs & Step Vans",
        "fleet-cdv-desc": "Versatile delivery vehicles built for the modern route.",
        "fleet-workflow": "Great Workflow",
        "fleet-workflow-desc": "Structured and seamless daily operations.",
        "fleet-lang": "Multilingual Team",
        "fleet-lang-desc": "Clear communication in English and Spanish.",
        
        "sec-safety-title": "Safety & Compliance is Non-Negotiable",
        "safety-text": "We maintain strict adherence to A&A Xpress and Amazon rules. Each vehicle is equipped with Netradyne cameras and Geotab tracking to monitor driving behaviors, ensuring total safety on the road. We operate a metric-based performance culture.",
        
        "sec-careers-title": "Careers",
        "careers-text": "We are looking for individuals with a positive attitude, whether with or without previous experience. At A&A Xpress, we offer competitive benefits:",
        "car-payrate": "Starting at $21.25/hr",
        "car-pay": "Weekly Pay",
        "car-bonuses": "Performance Bonuses",
        "car-flex": "Flexible Schedules",
        "car-tuition": "$5,250 in upfront tuition or tuition reimbursement each coverage year",
        "car-health": "Health, Vision & Dental Insurance",
        "car-pto": "Paid Time Off (PTO)",
        "car-401k": "401k",
        "car-full": "Full Time",
        "car-part": "Part Time",
        "car-training": "Paid training",
        "car-referral": "Referral program",
        "btn-apply": "Join the Team",
        "btn-indeed": "Apply on Indeed",
        
        "req-title": "Requirements",
        "req-1": "Valid U.S. Driver's License",
        "req-2": "Valid U.S. Work Permit",
        "req-3": "Must be 21 years of age or older",
        "req-4": "Must pass Drug Test & Background Check",
        "req-5": "Must have availability on Weekends",

        "sec-team-title": "Meet The Team",
        "team-name-owner": "Anthony Laury",
        "team-role-owner": "Owner",
        "team-name-coowner": "Anita Easter",
        "team-role-coowner": "Chief of Operations",
        "team-name-gm": "Larry Waldo",
        "team-role-gm": "General Manager",
        "team-name-om": "Jorge Reyes",
        "team-role-om": "Operations Manager",
        "team-name-hr": "Yvonne Easter",
        "team-role-hr": "HR Manager",
        "team-name-ha": "Alvaro Jaramillo",
        "team-role-ha": "HR Assistant",

        "sec-contact-title": "Contact Us",
        "contact-address-1": "DJX4 - 450 General Doolittle Dr, Jacksonville, FL 32225",
        "contact-address-2": "DJX3 - 250 Busch Dr, Jacksonville, FL 32218",
        
        "pos-driver": "Delivery Driver",
        "pos-dispatcher": "Dispatcher",
        "form-title": "Apply / Send Message",
        "form-subtitle": "Couldn't reach us? Leave your information here and we will get back to you.",
        "form-name": "Full Name",
        "form-phone": "Phone Number",
        "form-email": "Email Address",
        "form-resume": "Resume / CV (Optional)",
        "form-msg": "Message (Optional)",
        "form-submit": "Send Message",
        "footer-copy": "© 2026 A&A Xpress Inc. All rights reserved."
    },
    es: {
        "nav-about": "Nuestra Historia",
        "nav-fleet": "Flota y Seguridad",
        "nav-careers": "Empleos",
        "nav-team": "Conoce al Equipo",
        "nav-contact": "Contacto",
        "hero-quote-1": "\"We deliver packages for Amazon, we don't bring 'em back!\"",
        "hero-quote-1-author": "- Anthony Laury 2018",
        "hero-quote-4": "\"Delivering packages for Amazon is a job, it’s my job to turn delivery into a career!\"",
        "hero-quote-3": "- Anthony Laury 2023",
        "hero-subtitle": "Somos un Amazon DSP desarrollando una cultura basada en la seguridad y la eficiencia con la mirada puesta en el futuro de la logística. Únete a nuestro equipo hoy.",
        "btn-join": "Únete al Equipo",
        "btn-contact": "Contáctanos",
        
        "sec-about-title": "Nuestra Historia",
        "about-who-title": "Quiénes Somos",
        "about-who-text": "A&A Xpress es un Delivery Service Partner (DSP) independiente que trabaja con Amazon, operando desde Jacksonville, Florida. Somos responsables de las operaciones de entrega de última milla, asegurando que los paquetes lleguen a los clientes de forma segura. Nuestro equipo se basa en la estructura, la responsabilidad y un compromiso con la excelencia operativa.",
        "about-diff-title": "Qué Nos Diferencia",
        "about-diff-text": "En A&A Xpress, no solo entregamos paquetes — ejecutamos una operación estructurada y basada en datos. Utilizamos métricas de rendimiento y sistemas internos para tomar decisiones en tiempo real y apoyar a nuestros conductores todos los días. Ofrecemos un camino claro de crecimiento hacia roles de liderazgo.",
        "about-values-title": "Nuestros Valores Principales",
        
        "val-safe": "Safety First (Seguridad)",
        "val-safe-desc": " - Priorizamos la conducción segura y la entrega responsable en todo momento.",
        "val-team": "Teamwork (Trabajo en Equipo)",
        "val-team-desc": " - Operamos como un equipo, apoyándonos mutuamente para triunfar a diario.",
        "val-acc": "Accountability (Responsabilidad)",
        "val-acc-desc": " - Asumimos la responsabilidad de nuestro desempeño y resultados.",
        "val-grow": "Growth & Development (Crecimiento)",
        "val-grow-desc": " - Brindamos oportunidades de progreso profesional dentro de la empresa.",
        "val-exc": "Excellence in Execution (Excelencia)",
        "val-exc-desc": " - Nuestro objetivo es entregar con el estándar más alto, todos los días.",

        "sec-fleet-title": "Flota y Operaciones",
        "fleet-edv": "Rivian EDVs",
        "fleet-edv-desc": "La mayor parte de nuestra flota, impulsando la logística de cero emisiones.",
        "fleet-cdv": "CDVs y Step Vans",
        "fleet-cdv-desc": "Vehículos de entrega versátiles listos para cualquier ruta.",
        "fleet-workflow": "Gran Flujo de Trabajo",
        "fleet-workflow-desc": "Operaciones diarias fluidas y bien estructuradas.",
        "fleet-lang": "Equipo Multilingüe",
        "fleet-lang-desc": "Comunicación clara en Inglés y Español.",

        "sec-safety-title": "La Seguridad y Regulación no son Negociables",
        "safety-text": "Mantenemos un estricto cumplimiento de las normas de A&A Xpress y Amazon. Cada vehículo está equipado con cámaras Netradyne y rastreo Geotab para monitorear el manejo, garantizando total seguridad en la vía. Operamos con una cultura de desempeño basada en métricas.",

        "sec-careers-title": "Empleos",
        "careers-text": "Buscamos personas con actitud positiva, con o sin experiencia. En A&A Xpress, ofrecemos grandes beneficios:",
        "car-payrate": "Comenzando a $21.25/hr",
        "car-pay": "Pago Semanal",
        "car-bonuses": "Bonos por Desempeño",
        "car-flex": "Horarios Flexibles",
        "car-tuition": "$5,250 de matrícula por adelantado o reembolso cada año de cobertura",
        "car-health": "Seguro Médico, de Visión y Dental",
        "car-pto": "Paid Time Off (PTO)",
        "car-401k": "401k",
        "car-full": "Full Time",
        "car-part": "Part Time",
        "car-training": "Entrenamiento pagado",
        "car-referral": "Programa de referidos",
        "btn-apply": "Únete al Equipo",
        "btn-indeed": "Aplicar en Indeed",

        "req-title": "Requisitos Mínimos",
        "req-1": "Licencia de conducir válida para EE. UU.",
        "req-2": "Permiso de trabajo válido para EE. UU.",
        "req-3": "Ser mayor de 21 años",
        "req-4": "Pasar prueba de drogas y antecedentes",
        "req-5": "Disponibilidad obligatoria los fines de semana",

        "sec-team-title": "Conoce Al Equipo",
        "team-name-owner": "Anthony Laury",
        "team-role-owner": "Owner",
        "team-name-coowner": "Anita Easter",
        "team-role-coowner": "Chief of Operations",
        "team-name-gm": "Larry Waldo",
        "team-role-gm": "General Manager",
        "team-name-om": "Jorge Reyes",
        "team-role-om": "Operations Manager",
        "team-name-hr": "Yvonne Easter",
        "team-role-hr": "HR Manager",
        "team-name-ha": "Alvaro Jaramillo",
        "team-role-ha": "HR Assistant",

        "sec-contact-title": "Contáctanos",
        "contact-address-1": "DJX4 - 450 General Doolittle Dr, Jacksonville, FL 32225",
        "contact-address-2": "DJX3 - 250 Busch Dr, Jacksonville, FL 32218",

        "pos-driver": "Delivery Driver",
        "pos-dispatcher": "Dispatcher",
        "form-title": "Aplicar / Enviar Mensaje",
        "form-subtitle": "¿No pudiste contactarnos? Déjanos tu información aquí y te contactaremos.",
        "form-name": "Nombre Completo",
        "form-phone": "Número de Teléfono",
        "form-email": "Correo Electrónico",
        "form-resume": "Currículum / CV (Opcional)",
        "form-msg": "Mensaje (Opcional)",
        "form-submit": "Enviar Mensaje",
        "footer-copy": "© 2026 A&A Xpress Inc. Todos los derechos reservados."
    }
};

window.translations = translations;
